version: "3"

services:
  sonarqube:
    image: sonarqube:community
    environment:
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
      - SONAR_JDBC_URL=jdbc:postgresql://182.184.67.82:9030/sonarqube
      - SONAR_WEB_HOST=0.0.0.0
      - SONAR_WEB_PORT=9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
